spring:
  config:
    activate:
      on-profile: server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_JDBC_URL}   # H2 DB 연결 주소 (In-Memory Mode)
    username: ${DB_USER}        # H2 DB 접속 ID (사용자 지정)
    password: ${DB_PASSWORD}        # H2 DB 접속 PW (사용자 지정)