spring:
  datasource:
    url: jdbc:mysql://localhost:3306/worrybox #${DB_JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: true
  ai:
    openai:
      api-key: ${api-key}
      chat:
        options:
          model: gpt-3.5-turbo
server:
  port: 8080
  forward-headers-strategy: framework
# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enable: true
  cache:
    disabled: true
  use-fqn: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8